merged r413-417
git-svn-id: https://tmp.openrtm.org/svn/rtmtools/branches@418 16521fb8-224f-4d59-aec7-8b1ded20d512

diff --git a/RELENG_1_1/rtmtools/make_packages b/RELENG_1_1/rtmtools/make_packages
--- a/RELENG_1_1/rtmtools/make_packages
+++ b/RELENG_1_1/rtmtools/make_packages
@@ -108,11 +108,11 @@ PLUGINS="org.eclipse.emf.sdk.feature.group
          org.eclipse.xsd.sdk.feature.group"
 
 # Language package information
-# true ${LANGPACK_URL:="http://sourceforge.jp/projects/mergedoc/svn/view/trunk/Pleiades/build/pleiades.zip?view=co&root=mergedoc"}
-true ${LANGPACK_URL:="http://jaist.dl.sourceforge.jp/blancofw/56316/NLpackja-eclipse-SDK-3.8.0-blancofw20120628.zip"}
-# true ${LANGPACK_FILE_NAME:="pleiades.zip"}
-true ${LANGPACK_FILE_NAME:="NLpackja-eclipse-SDK-3.8.0-blancofw20120628.zip"}
-#true ${PLEIADES:="YES"}
+true ${LANGPACK_URL:="http://sourceforge.jp/projects/mergedoc/svn/view/trunk/Pleiades/build/pleiades.zip?view=co&root=mergedoc"}
+#true ${LANGPACK_URL:="http://jaist.dl.sourceforge.jp/blancofw/56316/NLpackja-eclipse-SDK-3.8.0-blancofw20120628.zip"}
+true ${LANGPACK_FILE_NAME:="pleiades.zip"}
+#true ${LANGPACK_FILE_NAME:="NLpackja-eclipse-SDK-3.8.0-blancofw20120628.zip"}
+true ${PLEIADES:="YES"}
 # openrtp tool information
 HERE=`pwd`
 true ${OPENRTP_SITE:="file:${HERE}/sitetool/openrtp_site"}
@@ -293,6 +293,16 @@ install_plugins()
     cmd="java -jar $EQUINOX_LAUNCHER"
     app_opt="-application org.eclipse.equinox.p2.director"
     dest_opt="-destination $WORK_DIR/eclipse"
+
+    scheme=`echo $REPOSITORY | egrep '^(http|https|ftp|file):\/\/'`
+    if test "x$scheme" = "x" ; then
+        # is local file?
+        is_abs=`echo $REPOSITORY | grep '^\/'`
+        if test "x$is_abs" = "x" ; then
+            REPOSITORY=`pwd`/$REPOSITORY
+        fi
+        REPOSITORY="file://$REPOSITORY"
+    fi
     repo_opt="-repository $REPOSITORY"
 
     for p in $PLUGINS ; do
@@ -432,6 +442,7 @@ apply_langpack()
             echo "Unzipping $LANGPACK_FILE_NAME failed. Aborting."
             exit 1
         fi
+
         echo "Applying langpack: Activating pleiades plugin."
         pleiades_jar="plugins/jp.sourceforge.mergedoc.pleiades/pleiades.jar"
         if test "x$OS" = "xMACOS" ; then
@@ -441,11 +452,19 @@ apply_langpack()
             echo "-javaagent:$pleiades_jar" \
                 >> $WORK_DIR/eclipse/eclipse.ini
         fi
+
         echo "Applying langpack: Modifying pleiades exclude properties."
         pleiades_pkg="jp.sourceforge.mergedoc.pleiades"
         pleiades_conf="${WORK_DIR}/eclipse/plugins/${pleiades_pkg}/conf"
         exclude_prop="${pleiades_conf}/translation-exclude-package.properties"
         echo "default=jp.go.aist.rtm.systemeditor" >> $exclude_prop
+
+        echo "Applying patch for pleiades-config.xml"
+        patch $pleiades_conf/pleiades-config.xml pleiades-config.xml.patch
+        if test $? -ne 0 ; then
+            echo "Patching failed. Aborting."
+            exit 1
+        fi
     else
         unzip -o $WORK_DIR/$LANGPACK_FILE_NAME -d $WORK_DIR
         if test $? -ne 0 ; then
